export const productos = [
    {
        id:1,
        marca:"Nike",
        modelo: "Air Max Tricolor",
        precio:7500,
        stock:7,
        img:"airmaxtri.jpeg",
    },
    {
        id:2,
        marca:"Nike",
        modelo: "Jordan Low Roja",
        precio:7600,
        stock:3,
        img:"jordanlowroja.jpg",
    },
    {
        id:3,
        marca:"Puma",
        modelo: "Rsx Negra",
        precio:7800,
        stock:6,
        img:"pumasrsx.jpeg",
    },
    {
        id:4,
        marca:"Nike",
        modelo: "SB Dunk Low Pigeon Premium",
        precio:8900,
        stock:2,
        img:"nikesb.jpeg",
    },
    {
        id:5,
        marca:"Alexander",
        modelo: "Mcqueen",
        precio:7200,
        stock:3,
        img:"alexander.jpeg",
    },
    {
        id:6,
        marca:"Vans",
        modelo: "Old Skool",
        precio:7000,
        stock:10,
        img:"vans.jpeg",
    },

]